name: Auto deployment on PRELIVE
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_PRELIVE_KEY" > ./deploy.key
        sudo chmod 600 ./deploy.key
        echo "$DEPLOY_PRELIVE_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        DEPLOY_PRELIVE_KEY: ${{secrets.DEPLOY_PRELIVE_KEY}}
        DEPLOY_PRELIVE_KNOWN_HOSTS: ${{secrets.DEPLOY_PRELIVE_KNOWN_HOSTS}}
    - name: Install PM2
      run: npm i -g pm2
    - name: Deployment
      run: pm2 deploy ecosystem.config.js prelive
      env:
        DEPLOY_PRELIVE_USER: ${{secrets.DEPLOY_PRELIVE_USER}}
        DEPLOY_PRELIVE_HOST: ${{secrets.DEPLOY_PRELIVE_HOST}}
        SERVER_HOST: ${{secrets.SERVER_PRELIVE_HOST}}
        SERVER_PORT: ${{secrets.SERVER_PRELIVE_PORT}}